# Site
#repository: sproogen/resume-theme
favicon: images/profile.jpeg

# Personal info
name: Ashwin Krishnamurthy
title: Senior Product Manager
#email: brett.h@email.co.uk
website: http://ashw.ink

# Social links
twitter_username: ashwinimitable
stackoverflow_username: ashwin-krishnamurthy
# github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: ashwinganeshk
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Greetings
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Ashwin is a Product Manager at Oracle and lives in San Jose, California, where he leads the next-generation of enterprise application development for Business Process Automation on the <mark>Cloud</mark>. He has advised two startups, worked as an Engineer, UI Developer and Product Manager in diverse industries ranging from <mark>Semiconductors</mark> to <mark>eCommerce</mark>.

  Outside of work, he is an avid reader and a podcast listener. He is passionate about teaching Computer Science and often volunteers at local schools and non-profits aimed at teaching the subject to young learners.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: Volunteering
# more_content: |

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
