# Site
#repository: sproogen/resume-theme
favicon: images/profile.jpeg

# Personal info
name: Ashwin Krishnamurthy
title: Senior Product Manager
#email: ashwin.ganesh.03@gmail.com
website: http://www.ashw.ink
darkmode: true
# Social links
twitter_username: ashwinimitable
stackoverflow_username: 653211
# github_username:
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: ashwinganeshk
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
about_title: About
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Ashwin is a Product Manager at Oracle and lives in San Jose, California, where he leads the next-generation of enterprise application development for Business Process Automation on the Cloud. He has advised two startups, worked as an Engineer, UI Developer and Product Manager in diverse industries ranging from Cyber Security to e-commerce.

  Outside of work, he is an avid reader and a podcast listener. He is passionate about teaching Computer Literacy and often volunteers at local schools and non-profits aimed at teaching Computer Science to young learners.

# Projects Section
projects_title: Achievements

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: Volunteering
# more_content: |

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-them
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
